/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {
  public static void main(String[] args)throws InterruptedException {
    ChromeOptions options = new ChromeOptions();
    WebDriver driver = new ChromeDriver(options);

     WebDriverManager.chromedriver().setup();
     //WebDriver driver = new ChromeDriver(options);

     driver.manage().window().maximize();

     TestCases tests = new TestCases(); // Initialize your test class    

     tests.testCase01();

    //END Tests
    tests.endTest();
       
    }
}
